// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtx9Y_XS3pnpqEkTT_KUbsshUS65o5zyw',
    appId: '1:1095490596290:web:f6b898e4e74972344efa5b',
    messagingSenderId: '1095490596290',
    projectId: 'chatapp-a8508',
    authDomain: 'chatapp-a8508.firebaseapp.com',
    storageBucket: 'chatapp-a8508.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9dzzan4kqWalfRypAHJG596SIiJhdtFQ',
    appId: '1:1095490596290:android:51a68e5eb244a54b4efa5b',
    messagingSenderId: '1095490596290',
    projectId: 'chatapp-a8508',
    storageBucket: 'chatapp-a8508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdpIudmKyStrKrs_xflUgiMeKzqLg8Ahw',
    appId: '1:1095490596290:ios:6d321489c28be8f64efa5b',
    messagingSenderId: '1095490596290',
    projectId: 'chatapp-a8508',
    storageBucket: 'chatapp-a8508.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdpIudmKyStrKrs_xflUgiMeKzqLg8Ahw',
    appId: '1:1095490596290:ios:6d321489c28be8f64efa5b',
    messagingSenderId: '1095490596290',
    projectId: 'chatapp-a8508',
    storageBucket: 'chatapp-a8508.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
